title: Grana.io
description: > # this means to ignore newlines until "baseurl:"
  Simplifique suas finanças
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://grana.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ":title"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
